apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      cpuset-scheduler: "true"
      podpreset.admission.kubernetes.io/podpreset-tz-default: "2148622"
    creationTimestamp: "2020-06-11T13:44:47Z"
    generateName: wrk-qa-86d8df49cc-
    labels:
      app: wrk-qa
      pod-template-hash: 86d8df49cc
    name: wrk-qa-86d8df49cc-4jvn7
    namespace: qa
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: wrk-qa-86d8df49cc
      uid: d108d01b-abd3-11ea-a750-00163e0dc939
    resourceVersion: "126173698"
    selfLink: /api/v1/namespaces/qa/pods/wrk-qa-86d8df49cc-4jvn7
    uid: b6c6d805-abe9-11ea-a750-00163e0dc939
  spec:
    containers:
    - args:
      - /data/.k8s/init_pod.sh
      command:
      - /bin/sh
      env:
      - name: YMM_MEMORY_SIZE
        value: 6144Mi
      - name: YMM_LANE
        value: default
      - name: YMM_TASK_ID
        value: "271718"
      - name: CpuCoreMax
        value: "4"
      - name: TZ
        value: Asia/Shanghai
      - name: LANG
        value: en_US.UTF-8
      - name: LC_ALL
        value: en_US.UTF-8
      - name: AppName
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: PodIp
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.podIP
      - name: EndPoint
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: YmmEnv
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      image: harbor.ymmoa.com/app/wrk:jar-master-jdk8-20200604_113121
      imagePullPolicy: Always
      lifecycle:
        preStop:
          exec:
            command:
            - /bin/sh
            - /data/.k8s/prestop.sh
      livenessProbe:
        exec:
          command:
          - /bin/sh
          - /data/beidou/control.sh
          - status
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: wrk-qa
      readinessProbe:
        exec:
          command:
          - /bin/sh
          - /data/beidou/control.sh
          - ready
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: "4"
          memory: 6Gi
        requests:
          cpu: "4"
          memory: 6Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/timezone
        name: tz-config2
      - mountPath: /etc/localtime
        name: tz-config
      - mountPath: /data/k8s-logs
        name: mydisk
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-cl2h2
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: qa.op.k8s.008155.hz
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 120
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - hostPath:
        path: /etc/timezone
        type: ""
      name: tz-config2
    - hostPath:
        path: /etc/localtime
        type: ""
      name: tz-config
    - hostPath:
        path: /data/k8s-logs
        type: DirectoryOrCreate
      name: mydisk
    - name: default-token-cl2h2
      secret:
        defaultMode: 420
        secretName: default-token-cl2h2
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2020-06-11T13:44:47Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2020-06-11T13:44:50Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2020-06-11T13:44:50Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2020-06-11T13:44:47Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://65d3342c598e48d69d3cf0469de91ea40a4297043de1a75d93ad0210e83f00d5
      image: harbor.ymmoa.com/app/wrk:jar-master-jdk8-20200604_113121
      imageID: docker-pullable://harbor.ymmoa.com/app/wrk@sha256:6f2e3f69e4799c2dc3dd6bd897a23ea3daf8b0e122e13be4362ed083d8f5cefb
      lastState: {}
      name: wrk-qa
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: "2020-06-11T13:44:48Z"
    hostIP: 10.100.8.155
    phase: Running
    podIP: 10.101.205.236
    qosClass: Guaranteed
    startTime: "2020-06-11T13:44:47Z"
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      cpuset-scheduler: "true"
      podpreset.admission.kubernetes.io/podpreset-tz-default: "2148622"
    creationTimestamp: "2020-06-11T13:45:57Z"
    generateName: wrk-qa-86d8df49cc-
    labels:
      app: wrk-qa
      pod-template-hash: 86d8df49cc
    name: wrk-qa-86d8df49cc-q88l6
    namespace: qa
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: wrk-qa-86d8df49cc
      uid: d108d01b-abd3-11ea-a750-00163e0dc939
    resourceVersion: "126174578"
    selfLink: /api/v1/namespaces/qa/pods/wrk-qa-86d8df49cc-q88l6
    uid: e0fd8d4c-abe9-11ea-a750-00163e0dc939
  spec:
    containers:
    - args:
      - /data/.k8s/init_pod.sh
      command:
      - /bin/sh
      env:
      - name: YMM_MEMORY_SIZE
        value: 6144Mi
      - name: YMM_LANE
        value: default
      - name: YMM_TASK_ID
        value: "271718"
      - name: CpuCoreMax
        value: "4"
      - name: TZ
        value: Asia/Shanghai
      - name: LANG
        value: en_US.UTF-8
      - name: LC_ALL
        value: en_US.UTF-8
      - name: AppName
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: PodIp
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.podIP
      - name: EndPoint
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: YmmEnv
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      image: harbor.ymmoa.com/app/wrk:jar-master-jdk8-20200604_113121
      imagePullPolicy: Always
      lifecycle:
        preStop:
          exec:
            command:
            - /bin/sh
            - /data/.k8s/prestop.sh
      livenessProbe:
        exec:
          command:
          - /bin/sh
          - /data/beidou/control.sh
          - status
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: wrk-qa
      readinessProbe:
        exec:
          command:
          - /bin/sh
          - /data/beidou/control.sh
          - ready
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: "4"
          memory: 6Gi
        requests:
          cpu: "4"
          memory: 6Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/timezone
        name: tz-config2
      - mountPath: /etc/localtime
        name: tz-config
      - mountPath: /data/k8s-logs
        name: mydisk
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-cl2h2
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: qa.op.k8s.008155.hz
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 120
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - hostPath:
        path: /etc/timezone
        type: ""
      name: tz-config2
    - hostPath:
        path: /etc/localtime
        type: ""
      name: tz-config
    - hostPath:
        path: /data/k8s-logs
        type: DirectoryOrCreate
      name: mydisk
    - name: default-token-cl2h2
      secret:
        defaultMode: 420
        secretName: default-token-cl2h2
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2020-06-11T13:45:57Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2020-06-11T13:46:06Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2020-06-11T13:46:06Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2020-06-11T13:45:57Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://6ad780a93c0dbe315aca23fa14635ee8618258f6b1434ddbfe2f39eb2fc4ddbd
      image: harbor.ymmoa.com/app/wrk:jar-master-jdk8-20200604_113121
      imageID: docker-pullable://harbor.ymmoa.com/app/wrk@sha256:6f2e3f69e4799c2dc3dd6bd897a23ea3daf8b0e122e13be4362ed083d8f5cefb
      lastState: {}
      name: wrk-qa
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: "2020-06-11T13:45:59Z"
    hostIP: 10.100.8.155
    phase: Running
    podIP: 10.101.205.239
    qosClass: Guaranteed
    startTime: "2020-06-11T13:45:57Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""